[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = ".git"
python_files = "test_*.py"

[tool.coverage.run]
source = "custom_components"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "pass",
    "raise ImportError",
]