[![hacs_badge](https://img.shields.io/badge/HACS-Custom-orange.svg)](https://github.com/custom-components/hacs)
[![hassfest validation](https://github.com/GrumpyTanker/hydrolink-hacs/workflows/Validate%20with%20hassfest/badge.svg)](https://github.com/GrumpyTanker/hydrolink-hacs/actions/workflows/hassfest.yaml)
[![HACS validation](https://github.com/GrumpyTanker/hydrolink-hacs/workflows/HACS%20Validation/badge.svg)](https://github.com/GrumpyTanker/hydrolink-hacs/actions/workflows/hacs.yaml)

name: HACS Validation

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"